### ISSUE TITLE
Project 

### ISSUE THREAD

**Issue by yaelarieli** [Mahers7/Mahers7.github.io#1]
Hi Mahers,
I'm Yael; I also take the Wis Python course.

Gabor asked to send our project to a student to get feedback, can you look at my project?
 
I need to submit my project by next week cause I will be abroad, so if you don't have time before to check it, I would appreciate it if you let me know so I can look for someone else.

This is the link for my project:
[project](https://github.com/yaelarieli/Project---WIS-Python-course
)
Thanks!!

**Comment by Mahers7** [comment]
Hi Yael,

I tried to run your project also with your netCDF file and other from the internet but it didn't work for me I don't know maybe I'm doing sth wrong, but this is what it give me.

File "C:\work\Python_assignments\project\yael.py", line 63, in <module>
    main()
  File "C:\work\Python_assignments\project\yael.py", line 28, in main
    Qp = ds.Qp
         ^^^^^
  File "C:\Users\Maher\AppData\Local\Programs\Python\Python312\Lib\site-packages\xarray\core\common.py", line 285, in __getattr__
    raise AttributeError(
AttributeError: 'Dataset' object has no attribute 'Qp'

**Comment by yaelarieli** [comment]
Hi,
Thank you!
It cannot work with any netCDF file. When you try with the file I uploaded (data_for_AFcalc.nc)
you get the same error?

**Comment by Mahers7** [comment]
not the same,
Error opening file '.\data_for_AFcalc_test.nc': did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'scipy']. Consider explicitly selecting one of the installed engines via the
 ``engine`` parameter, or installing additional IO dependencies,
maybe you can send me the file on mail maher.salhab@weizmann.ac.il

**Comment by Mahers7** [comment]
not the same, 

PS C:\work\Python_assignments\project> python .\yael.py .\data_for_AFcalc.nc
Error opening file '.\data_for_AFcalc.nc': did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'scipy']. Consider explicitly selecting one of the installed engines via the ``en
gine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html
PS C:\work\Python_assignments\project> python .\yael.py data_for_AFcalc.nc -zb
usage: yael.py [-h] [--CloudBase CLOUDBASE] [--CorePercentage COREPERCENTAGE] filename
yael.py: error: unrecognized arguments: -zb
PS C:\work\Python_assignments\project>

maybe you can send me the file on mail maher.salhab@weizmann.ac.il

**Comment by Mahers7** [comment]
Hi Yael, 

everything looks good it work for me , good luck.

**Comment by yaelarieli** [comment]
Thank you very much!!
